### ISSUE TITLE
track.cpp:43:11: fatal error: 'config.h' file not found

### ISSUE THREAD

**Issue by vicsandr** [ponchio/untrunc#104]
Having a devil of a time compiling this on Mac OS 10.11.6 El Capitan. 
This is what I tried and the subsequent result:
$ g++ -o untrunc file.cpp main.cpp track.cpp atom.cpp mp4.cpp -L/usr/local/lib -lavformat -lavcodec -lavutil
track.cpp:43:11: fatal error: 'config.h' file not found
# include <config.h>
          ^
1 error generated.
mp4.cpp:293:46: warning: 'codec' is deprecated [-Wdeprecated-declarations]
                track.codec.context = context->streams[i]->codec;
                                                           ^
/usr/local/include/libavformat/avformat.h:893:21: note: 'codec' has been
      explicitly marked deprecated here
    AVCodecContext *codec;
                    ^
1 warning generated.
ESF-POST:untrunc-master vicsandr$ g++ -o untrunc file.cpp main.cpp track.cpp atom.cpp mp4.cpp -L/usr/local/lib -lavformat -lavcodec -lavutil
track.cpp:43:11: fatal error: 'config.h' file not found
# include <config.h>
          ^
1 error generated.
mp4.cpp:293:46: warning: 'codec' is deprecated [-Wdeprecated-declarations]
                track.codec.context = context->streams[i]->codec;
                                                           ^
/usr/local/include/libavformat/avformat.h:893:21: note: 'codec' has been explicitly marked deprecated here
    AVCodecContext *codec;
                    ^
1 warning generated.
ESF-POST:untrunc-master vicsandr$  g++ -o untrunc file.cpp main.cpp track.cpp atom.cpp mp4.cpp -I./libav-12.2 -L./libav-12.2/libavformat -lavformat -L./libav-12.2/libavcodec -lavcodec -L./libav-12.2/libavresample -lavresample -L./libav-12.2/libavutil -lavutil -lpthread -lz -framework CoreFoundation -framework CoreVideo -framework VideoDecodeAcceleration -lbz2
track.cpp:43:11: fatal error: 'config.h' file not found
# include <config.h>
          ^
1 error generated.
mp4.cpp:293:46: warning: 'codec' is deprecated [-Wdeprecated-declarations]
                track.codec.context = context->streams[i]->codec;
                                                           ^
/usr/local/include/libavformat/avformat.h:893:21: note: 'codec' has been explicitly marked deprecated here
    AVCodecContext *codec;
                    ^
1 warning generated.

Any help would be appreciated. Thanks.

**Comment by ponchio** [comment]
Ciao,
        in my code I am doing some horrible hacks that the god of coding
won't forgive me for.

I'm using some internal files (which are not supposed to be exported by the
library), actually C files, through some
dark magic #define. Depending on how the library was compiled and where the
config.h might be present or not,
some libs (bz2 for example) might be needed or not.

So I am fully aware of how messy the compilation can be. I lack
alternatives, though (or I am just a tad out of my league).

Have you tried changinf this line (track.cpp line: 45)

#if LIBAVCODEC_VERSION_MAJOR != 56 //ubuntu 16.04 version\

into

#if 0

to take the #else path, which doesn't expect the config.h ?
You might also need to use some of the tricks in the first branch.

Otherwise, just send me the files and I wiill see if I can fix them (if it
works it takes just a few minutes).

Ciao and good luck,

Federico

**Comment by Gasparbsurde** [comment]
Hello,
I'm having the exact same issue on Ubuntu 17.10.
I've tried to turn line 45 from:
`#if LIBAVCODEC_VERSION_MAJOR != 56 //ubuntu 16.04 version\`
into:
`#if 0`
but it only change the fatal error into:
`track.cpp:60:10: fatal error: libavcodec/h264dec.h: No file or folder of this type`
 `#include <libavcodec/h264dec.h>`

As i'm not a C++ guru, some help would be much appreciated :).

**Comment by brandon-dacrib** [comment]
I recommend using the docker build which was recently merged into master
