### ISSUE TITLE
Produces an MP4 file with one frame (but I see it!) then stops.

### ISSUE THREAD

**Issue by jorvis** [ponchio/untrunc#256]
Trying to repair a tutorial created with VokoscreenNG, which crashed while writing the video.  Here's me running it:

$ untrunc eve_dojo_intro_video.mp4 fixmeplease.mp4 
Reading: eve_dojo_intro_video.mp4
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x55d450e89ac0] be7acfcb97a942e89c71999491e3afac
Repair: fixmeplease.mp4
Mdat not found!
Backtracked enough!
Found 4 packets.
Found 3 chunks for avc1
Found 1 chunks for mp4a
Saving to: fixmeplease_fixed.mp4

Then the resulting file sizes:

$ ls -l eve_dojo_intro_video.mp4 fixmeplease.mp4 fixmeplease_fixed.mp4
-rw-rw-r-- 1 jorvis jorvis  16380450 Mar  1 10:31 eve_dojo_intro_video.mp4
-rw-rw-r-- 1 jorvis jorvis    386791 Mar  3 01:47 fixmeplease_fixed.mp4
-rw-rw-r-- 1 jorvis jorvis 394156299 Mar  3 01:35 fixmeplease.mp4

The "fixed" version is super small, appearing to be the only frame but I *can* see my video correctly in that frame.

Thanks for the help!

**Comment by ponchio** [comment]
Finding the beginning of each packet requires some guesswork, and sometime the guess is wrong.
There could be many reasons:

1) Proprietary codec in the video.
2) Padding (with garbage sometimes)
3) Corrupted data.
4) Bug in parsing avc1.

Send me the files (broken and working), I will have a look at it, and see what the problem is and if it can be fixed. (and maybe improve the code).
(ponchio@gmail.com)

**Comment by jorvis** [comment]
Thank you, e-mail sent.

**Comment by rajhlinux** [comment]
Can you help me too?

**Comment by ponchio** [comment]
The problem was mp3 codec: it consumes all available buffer instead of just the length of the packet as other codecs do.
Last commit should fix this problem.

Rajhlinux just send me the files, I will have a look at them.

**Comment by jorvis** [comment]
Thanks for your work on this!
